# Generated by Django 3.2.8 on 2021-10-29 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('fax', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
                ('suppliers', models.ManyToManyField(to='main.Brand', verbose_name='suppliers')),
                ('user_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('deputy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrisonBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('branch_deputy', models.CharField(max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ordered_quantity', models.BigIntegerField(default=0, null=True)),
                ('based_quantity', models.CharField(choices=[('عدد', 'Each'), ('کارتن', 'Box'), ('کیلوگرم', 'Kg'), ('گرم', 'Gr'), ('تن', 'Tn'), ('متر', 'Meter')], default='عدد', max_length=20, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('percentage', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, null=True, unique=True)),
                ('user_signatures', models.BinaryField(default=b'\x80\x04\x95L\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x03ceo\x94N\x8c\x11financial_manager\x94N\x8c\x12commercial_manager\x94N\x8c\x11commercial_expert\x94Nu.', null=True)),
                ('request_status', models.CharField(choices=[('درحال بررسی توسط مدیر عامل', 'Ceo Review'), ('درحال بررسی توسط مدیر مالی', 'Fm Review'), ('درحال بررسی توسط مدیر بازرگانی', 'Cm Review'), ('درحال بررسی توسط کارشناس بازرگانی', 'Ce Review'), ('عدم تایید توسط مدیر عامل', 'Ceo Dreview'), ('عدم تایید توسط مدیر مالی', 'Fm Dreview'), ('عدم تایید توسط مدیر بازرگانی', 'Cm Dreview'), ('عدم تایید توسط کارشناس بازرگانی', 'Ce Dreview'), ('اتمام تاییدیه', 'Completed')], default='درحال بررسی توسط مدیر عامل', max_length=255)),
                ('shipping_status', models.CharField(choices=[('درحال تاییدیه', 'Requested'), ('در حال ارسال به تامین کنندگان', 'Supplier'), ('در حال آماده سازی سفارش', 'Gathering'), ('ارسال شده', 'Sending'), ('دریافت شده', 'Delivered'), ('تایید نشده', 'Declined')], default='درحال تاییدیه', max_length=50)),
                ('shipping_fee', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.prisonbranch')),
                ('expert', models.ManyToManyField(related_name='expert', to=settings.AUTH_USER_MODEL)),
                ('prison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.prison')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('province', models.CharField(max_length=30, null=True)),
                ('fax', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('margin', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 10, 29, 19, 4, 49, 986335))),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('price2m', models.BigIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 10, 29, 19, 4, 49, 988333))),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.request')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='prison',
            name='prisons',
            field=models.ManyToManyField(to='main.PrisonBranch', verbose_name='prisons'),
        ),
        migrations.AddField(
            model_name='prison',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.province'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.BigIntegerField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField(default=0)),
                ('price_2m', models.BigIntegerField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request', unique=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('reply', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('reply_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_user', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ticket')),
            ],
        ),
    ]
