# Generated by Django 3.2.6 on 2021-10-13 11:51

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 13, 15, 21, 48, 959523)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 21, 48, 959523)),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 21, 48, 959523)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 21, 48, 959523)),
        ),
    ]
