# Generated by Django 3.2.7 on 2021-10-14 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211013_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 10, 14, 15, 9, 44, 700015)),
        ),
        migrations.AlterField(
            model_name='product',
            name='based_quantity',
            field=models.CharField(choices=[('عدد', 'Each'), ('کارتن', 'Box'), ('کیلوگرم', 'Kg'), ('گرم', 'Gr'), ('تن', 'Tn')], default='عدد', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 39, 44, 695570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 9, 44, 701569)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 9, 44, 698043)),
        ),
    ]
