# Generated by Django 3.2.7 on 2021-10-14 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211014_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 45, 35, 164465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 45, 35, 159906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 15, 35, 165688)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 15, 35, 162333)),
        ),
    ]
