# Generated by Django 3.2.7 on 2021-10-14 11:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20211014_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='expert',
            field=models.ManyToManyField(related_name='expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 18, 52, 335665)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 15, 18, 52, 332018)),
        ),
    ]
